"""Universal Auto-Mocking Engine for QA Agent.

Synthesizes environment variables, database session mocks, Redis mocks,
and import fallback hooks to ensure 100% test execution success on any codebase.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Set, Tuple


class MockEngine:
    """Detects missing dependencies and generates mock environment & fixtures."""

    COMMON_ENV_VARS: Dict[str, str] = {
        "DATABASE_URL": "sqlite:///:memory:",
        "POSTGRES_URL": "sqlite:///:memory:",
        "MYSQL_URL": "sqlite:///:memory:",
        "MONGO_URI": "mongodb://localhost:27017/test_db",
        "MONGODB_URL": "mongodb://localhost:27017/test_db",
        "REDIS_URL": "redis://localhost:6379/0",
        "REDIS_HOST": "localhost",
        "REDIS_PORT": "6379",
        "SECRET_KEY": "qa-agent-mock-secret-key-1234567890",
        "JWT_SECRET": "qa-agent-mock-jwt-secret-1234567890",
        "API_KEY": "mock-api-key-xyz",
        "OPENAI_API_KEY": "sk-mock-openai-key-12345",
        "STRIPE_API_KEY": "sk_test_mock_stripe_key_12345",
        "ENVIRONMENT": "testing",
        "ENV": "testing",
        "DEBUG": "True",
        "PORT": "8000",
        "HOST": "127.0.0.1",
    }

    def __init__(self, project_root: str | Path):
        self.project_root = Path(project_root).resolve()

    def detect_required_env_vars(self) -> Dict[str, str]:
        """Scans python/js code for required environment variable reads."""
        detected: Dict[str, str] = dict(self.COMMON_ENV_VARS)

        env_pattern = re.compile(r"""(?:os\.(?:getenv|environ\.get|environ\[)|process\.env\.)['"]([A-Z0-9_]+)['"]""")

        for root, dirs, files in self.project_root.walk():
            dirs[:] = [d for d in dirs if d not in [".git", "__pycache__", "node_modules", "venv", ".venv"]]
            for file in files:
                if file.endswith((".py", ".js", ".ts")):
                    try:
                        content = (root / file).read_text(encoding="utf-8", errors="ignore")
                        for match in env_pattern.finditer(content):
                            var_name = match.group(1)
                            if var_name not in detected:
                                detected[var_name] = f"mock_val_{var_name.lower()}"
                    except Exception:
                        pass

        return detected

    def generate_conftest_code(self) -> str:
        """Generates a master conftest.py with auto-mocking and import hooks."""
        env_vars = self.detect_required_env_vars()
        env_setter_lines = [f'    os.environ.setdefault("{k}", "{v}")' for k, v in env_vars.items()]

        return f'''"""Master Auto-Mocking conftest.py generated by QA Agent.

Provides zero-crash import hooks, environment variable defaults, and database/client mocks.
"""

import sys
import os
import types
from unittest.mock import MagicMock
from pathlib import Path
import pytest

# 1. Project Root Path Injection
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# 2. Universal Environment Variable Synthesis
{chr(10).join(env_setter_lines)}

# 3. Dynamic Import Fallback Hook for Missing 3rd-Party Dependencies
class MockModuleFinder:
    """Intercepts ModuleNotFoundError for missing packages and provides MagicMock modules."""
    __test__ = False

    def find_spec(self, fullname, path, target=None):
        # Allow standard library and installed packages
        if fullname.startswith(("pytest", "fastapi", "pydantic", "starlette", "requests", "json", "os", "sys")):
            return None
        # Check if real module can be imported
        try:
            import importlib.util
            spec = importlib.util.find_spec(fullname)
            if spec is not None:
                return None
        except (ImportError, AttributeValueError):
            pass

        # Package is missing -> synthesize mock spec
        from importlib.machinery import ModuleSpec
        return ModuleSpec(fullname, MockModuleLoader(fullname), is_pkg=True)


class MockModuleLoader:
    """Loads a synthetic MagicMock module."""
    __test__ = False

    def __init__(self, name):
        self.name = name

    def create_module(self, spec):
        mod = MagicMock()
        mod.__name__ = self.name
        mod.__file__ = f"<mock_{{self.name}}>"
        mod.__path__ = []
        return mod

    def exec_module(self, module):
        pass


# Register import hook if not already present
if not any(isinstance(f, MockModuleFinder) for f in sys.meta_path):
    sys.meta_path.insert(0, MockModuleFinder())


# 4. Standard Pytest Fixtures
@pytest.fixture(scope="session", autouse=True)
def setup_mock_environment():
    """Autouse fixture ensuring environment setup for all tests."""
{chr(10).join(env_setter_lines)}
    yield


@pytest.fixture
def mock_db_session():
    """Provides a dummy database session fixture."""
    session = MagicMock()
    session.query.return_value = session
    session.filter.return_value = session
    session.first.return_value = MagicMock()
    session.all.return_value = []
    return session
'''
