"""QA Report Generator.

Generates standalone Markdown and HTML reports from ExecutionResult.
"""

from __future__ import annotations

import datetime
from typing import Optional
from qa_agent.core.models import ExecutionResult, ProjectProfile, TestPlan


class QAReporter:
    """Creates formatted reports for test runs."""

    def __init__(self, profile: ProjectProfile, plan: Optional[TestPlan] = None):
        self.profile = profile
        self.plan = plan

    def generate_markdown_report(self, result: ExecutionResult) -> str:
        """Generates a GitHub-flavored Markdown report."""
        pass_rate = (
            round((result.passed / result.total_tests) * 100, 1)
            if result.total_tests > 0
            else (100.0 if result.success else 0.0)
        )
        status_emoji = "PASSED" if result.success else "FAILED"
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Build table of tests
        test_rows = []
        for item in result.test_items:
            badge = "PASSED" if item.status == "PASSED" else f"**{item.status}**"
            test_rows.append(f"| `{item.name}` | {badge} | `{item.suite or '-'}` |")

        test_table = chr(10).join(test_rows) if test_rows else "_No individual test items parsed._"

        md = f"""# QA Agent Automated Test Report

**Project:** {self.profile.project_name}  
**Date:** {timestamp}  
**Overall Status:** {status_emoji}  
**Execution Time:** {result.duration_seconds}s  
**Pass Rate:** {pass_rate}%  

---

## Executive Summary

| Total Tests | Passed | Failed | Skipped | Errors |
| :---: | :---: | :---: | :---: | :---: |
| **{result.total_tests}** | {result.passed} | {result.failed} | {result.skipped} | {result.errors} |

- **Primary Language:** {self.profile.primary_language}
- **Detected Frameworks:** {', '.join(self.profile.frameworks) or 'None'}
- **Command Executed:** `{result.command_executed}`
- **Exit Code:** `{result.exit_code}`

---

## Test Results Breakdown

| Test Name | Status | Suite File |
| :--- | :--- | :--- |
{test_table}

---

## Raw Execution Output

```text
{result.stdout.strip() or 'No standard output recorded.'}
```
"""
        if result.stderr.strip():
            md += f"""
### Errors / Stderr
```text
{result.stderr.strip()}
```
"""
        return md

    def generate_html_report(self, result: ExecutionResult) -> str:
        """Generates a standalone, beautiful HTML report."""
        pass_rate = (
            round((result.passed / result.total_tests) * 100, 1)
            if result.total_tests > 0
            else (100.0 if result.success else 0.0)
        )
        status_class = "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" if result.success else "bg-rose-500/10 text-rose-400 border-rose-500/20"
        status_text = "PASSED" if result.success else "FAILED"
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        test_rows_html = ""
        for item in result.test_items:
            badge_color = "bg-emerald-500/10 text-emerald-400" if item.status == "PASSED" else "bg-rose-500/10 text-rose-400"
            test_rows_html += f"""
            <tr class="border-b border-zinc-800 hover:bg-zinc-800/50">
                <td class="py-3 px-4 font-mono text-sm text-zinc-200">{item.name}</td>
                <td class="py-3 px-4"><span class="px-2.5 py-1 text-xs font-semibold rounded-full {badge_color}">{item.status}</span></td>
                <td class="py-3 px-4 font-mono text-xs text-zinc-400">{item.suite or '-'}</td>
            </tr>
            """

        html = f"""<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QA Report - {self.profile.project_name}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {{ background-color: #09090b; color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }}
    </style>
</head>
<body class="p-6 md:p-12 max-w-6xl mx-auto">
    <header class="flex flex-col md:flex-row md:items-center justify-between border-b border-zinc-800 pb-6 mb-8 gap-4">
        <div>
            <div class="flex items-center gap-3">
                <h1 class="text-2xl font-bold tracking-tight text-white">{self.profile.project_name}</h1>
                <span class="px-3 py-1 rounded-full text-xs font-semibold border {status_class}">{status_text}</span>
            </div>
            <p class="text-sm text-zinc-400 mt-1">Generated by QA Agent &bull; {timestamp}</p>
        </div>
        <div class="flex items-center gap-3 text-sm text-zinc-400">
            <span class="px-3 py-1.5 bg-zinc-900 border border-zinc-800 rounded-lg">{self.profile.primary_language}</span>
            <span class="px-3 py-1.5 bg-zinc-900 border border-zinc-800 rounded-lg">{result.duration_seconds}s</span>
        </div>
    </header>

    <!-- Metrics Grid -->
    <div class="grid grid-cols-2 sm:grid-cols-5 gap-4 mb-8">
        <div class="p-5 rounded-xl bg-zinc-900/60 border border-zinc-800">
            <div class="text-xs uppercase font-medium text-zinc-400">Total Tests</div>
            <div class="text-3xl font-bold text-white mt-1">{result.total_tests}</div>
        </div>
        <div class="p-5 rounded-xl bg-zinc-900/60 border border-zinc-800">
            <div class="text-xs uppercase font-medium text-emerald-400">Passed</div>
            <div class="text-3xl font-bold text-emerald-400 mt-1">{result.passed}</div>
        </div>
        <div class="p-5 rounded-xl bg-zinc-900/60 border border-zinc-800">
            <div class="text-xs uppercase font-medium text-rose-400">Failed</div>
            <div class="text-3xl font-bold text-rose-400 mt-1">{result.failed}</div>
        </div>
        <div class="p-5 rounded-xl bg-zinc-900/60 border border-zinc-800">
            <div class="text-xs uppercase font-medium text-amber-400">Skipped</div>
            <div class="text-3xl font-bold text-amber-400 mt-1">{result.skipped}</div>
        </div>
        <div class="p-5 rounded-xl bg-zinc-900/60 border border-zinc-800">
            <div class="text-xs uppercase font-medium text-indigo-400">Pass Rate</div>
            <div class="text-3xl font-bold text-indigo-400 mt-1">{pass_rate}%</div>
        </div>
    </div>

    <!-- Test List Table -->
    <div class="rounded-xl border border-zinc-800 bg-zinc-900/40 overflow-hidden mb-8">
        <div class="px-6 py-4 border-b border-zinc-800 font-semibold text-zinc-200">
            Test Execution Breakdown
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-left border-collapse">
                <thead>
                    <tr class="border-b border-zinc-800 text-xs uppercase text-zinc-400 bg-zinc-900/80">
                        <th class="py-3 px-4">Test Case</th>
                        <th class="py-3 px-4">Status</th>
                        <th class="py-3 px-4">Suite</th>
                    </tr>
                </thead>
                <tbody>
                    {test_rows_html if test_rows_html else '<tr><td colspan="3" class="py-6 text-center text-zinc-500">No test cases parsed</td></tr>'}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Raw Terminal Log -->
    <div class="rounded-xl border border-zinc-800 bg-zinc-950 p-4 font-mono text-xs text-zinc-300 overflow-x-auto">
        <div class="text-zinc-500 mb-2 font-sans font-semibold">Console Output:</div>
        <pre>{result.stdout.strip()}</pre>
    </div>
</body>
</html>
"""
        return html

